### ISSUE TITLE
SPA 도커 파일 작성 예제 만들기

### ISSUE THREAD

**Issue by yoonhona** [yoonhona/my-learning#1]
# 목표

- SPA 배포를 위한 도커 파일 작성
- 추후 블로그 작성을 위한 단계별 진행
- 단계
  1. 배포 용이 아닌 로컬 dev로 배포
  2. 적어도 배포 형태인 최소한의 nginx 서빙, 도커에서 빌드가 아닌 외부에서 빌드
  3. multistage를 사용한 빌드 후 nginx 서빙 

# todo

- [ ]: 요즘 많이 사용하는 vite 템플릿(리액트 + TS)으로  SPA
- [ ]: node 이미지를 사용하는 로컬 dev 모드로 도커 이미지 작성
- [ ]: github action에서 빌드 후 nginx로 배포하는 수준으로 업그레이드
- [ ]: 도커 파일 내부에서 빌드 후 nginx로 배포하는 multistage 이미지로 업그레이드
- [ ]: 추가 최적화가 필요한 부분들 업그레이드, alphine, nginx 최적화등
