### ISSUE TITLE
도커로 SPA 무중단 구성해보기

### ISSUE THREAD

**Issue by yoonhona** [yoonhona/my-learning#3]
# 목표

- 버전에 따라 SPA를 라우팅해주는 nginx 1개 컨테이너, 배포되는 버전 SPA 컨테이너, 라이브 중인 이전 버전 SPA 컨테이너, 총 3개의 컨테이너 구성
- docker compose로 그룹핑된 컨테이너를 무중단 배포해보고 블로그 글로 공유하기

# todo

- [ ] 라우팅 컨테이너 nginx 구성
- [ ] docker compose 구성
- [ ] 배포 구성
  - [ ] 무료 docker 서비스에 올리기
  - [ ] argo cd 로 무중단 CD 구성
- [ ] 블로그 글 작성
